# Generated by Django 5.0.1 on 2024-10-01 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('web_page', models.URLField()),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('web_page', models.URLField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crypto_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.crypto')),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin_market_cap', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='StocksHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin_market_cap', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchangeApp.favorites')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='exchangeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_histories', to='exchangeApp.offers')),
                ('wallet_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to='exchangeApp.wallet')),
                ('wallet_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_transactions', to='exchangeApp.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='publisherWallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchangeApp.wallet'),
        ),
        migrations.CreateModel(
            name='AssetsToWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsToFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.asset')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeApp.favorites')),
            ],
            options={
                'unique_together': {('favorite', 'asset')},
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('crypto_symbol__isnull', False), ('stock_symbol__isnull', False), _connector='OR'), name='at_least_one_symbol_must_be_present'),
        ),
        migrations.AlterUniqueTogether(
            name='assetstowallet',
            unique_together={('wallet', 'asset')},
        ),
    ]
