# Generated by Django 5.0.1 on 2024-09-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='stock',
        ),
    ]
