# Generated by Django 5.0.1 on 2024-09-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeApp', '0002_remove_asset_crypto_remove_asset_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptohistory',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
